#SENDER
###
POST http://localhost:8080/senderStart

###
POST http://localhost:8080/increase-speed
Content-Type: application/json

1

###
POST http://localhost:8080/decrease-speed
Content-Type: application/json

5

###
GET http://localhost:8080/current-speed

#TEST
###
GET http://localhost:8080/tasksList

###
POST http://localhost:8080/add
Content-Type: application/json

{
  "number": 293456419
}

###
GET http://localhost:8080/f45e9012-b5b8-4015-91b0-d9b9bc6ef10e






