#PROCESSOR
###
POST http://localhost:8080/addTaskProcessor

###
GET http://localhost:8080/current-count-processor

###
POST http://localhost:8080/increase-speed-processor
Content-Type: application/json

1

###
POST http://localhost:8080/decrease-speed-processor
Content-Type: application/json

1

###
GET http://localhost:8080/current-speed-processor






